proc sql;
   create table work.JOIN_EMR_CAD as
   select
      AMBO_EMR_NOCAD.EPCR_ID length = 8   
         format = BEST12.
         informat = BEST32.,
      AMBO_EMR_NOCAD.CASE_DATE length = 8   
         format = DATETIME.
         informat = ANYDTDTM40.,
      AMBO_EMR_NOCAD.CASE_NUMBER length = 8   
         format = BEST12.
         informat = BEST32.,
      AMBO_EMR_NOCAD.PT_RCD_ID length = 8   
         format = BEST12.
         informat = BEST32.,
      AMBO_EMR_NOCAD.CASE_GIVEN_AS length = 50   
         format = $50.
         informat = $50.,
      LND_EMR_LINKED_CAD.SCENE_LOCATION_NAME length = 56   
         format = $56.
         informat = $56.,
      LND_EMR_LINKED_CAD.SCENE_SUBURB length = 35   
         format = $35.
         informat = $35.,
      LND_EMR_LINKED_CAD.SCENE_POSTCODE length = 4   
         format = $4.
         informat = $4.,
      LND_EMR_LINKED_CAD.SCENE_STATE length = 28   
         format = $28.
         informat = $28.,
      AMBO_EMR_NOCAD.GENDER length = 13   
         format = $13.
         informat = $13.,
      AMBO_EMR_NOCAD.YEAR_AGE length = 8   
         format = BEST32.
         informat = BEST32.,
      LND_EMR_LINKED_CAD.NOT_TREATED_REASON length = 38   
         format = $38.
         informat = $38.,
      LND_EMR_LINKED_CAD.NOT_TRANSPORTED_REASON length = 29   
         format = $29.
         informat = $29.,
      LND_EMR_LINKED_CAD.Date_Response length = 8   
         format = DATETIME.
         informat = ANYDTDTM40.,
      LND_EMR_LINKED_CAD.Time_Response length = 8   
         format = DATETIME.
         informat = ANYDTDTM40.,
      LND_EMR_LINKED_CAD.Master_Incident_Number length = 8   
         format = BEST12.
         informat = BEST32.,
      LND_EMR_LINKED_CAD.Transport_Protocol length = 29   
         format = $29.
         informat = $29.,
      LND_EMR_LINKED_CAD.Problem length = 30   
         format = $30.
         informat = $30.,
      LND_EMR_LINKED_CAD.Pickup_Location length = 50   
         format = $50.
         informat = $50.,
      LND_EMR_LINKED_CAD.Pickup_Address length = 45   
         format = $45.
         informat = $45.,
      LND_EMR_LINKED_CAD.Pickup_City length = 35   
         format = $35.
         informat = $35.,
      LND_EMR_LINKED_CAD.Pickup_Postal_Code length = 10   
         format = $10.
         informat = $10.,
      LND_EMR_LINKED_CAD.PickupLong_Convert length = 10   
         format = $10.
         informat = $10.,
      LND_EMR_LINKED_CAD.PickupLat_Convert length = 10   
         format = $10.
         informat = $10.,
      AMBO_EMR_NOCAD.PREEXISTING_CONDITION_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.PREEXISTING_CONDITION_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.CASE_NATURE_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.CASE_NATURE_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.CASE_DESCRIPTION length = 2000   
         format = $2000.
         informat = $2000.,
      AMBO_EMR_NOCAD.COMPLAINT_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.COMPLAINT_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.PRIMARY_SURVEY_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.PRIMARY_SURVEY_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.SECONDARY_SURVEY_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.SECONDARY_SURVEY_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.ASSESSMENT_NAME length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.ASSESSMENT_SUMMARY length = 3000   
         format = $3000.
         informat = $3000.,
      AMBO_EMR_NOCAD.PROTOCOL_1 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_2 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_3 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_4 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_5 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_6 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.PROTOCOL_7 length = 6   
         format = $PROTOCOLS.
         informat = $6.,
      AMBO_EMR_NOCAD.CASE_YEAR length = 8   
         format = BEST32.
         informat = BEST32.
   from
      SPNSW_LN.AMBO_EMR_NOCAD as AMBO_EMR_NOCAD left join 
      SPNSW_LN.LND_EMR_LINKED_CAD as LND_EMR_LINKED_CAD
         on
         (
            AMBO_EMR_NOCAD.EPCR_ID = LND_EMR_LINKED_CAD.EPCR_ID
            and AMBO_EMR_NOCAD.CASE_DATE = LND_EMR_LINKED_CAD.CASE_DATE
            and AMBO_EMR_NOCAD.CASE_NUMBER = LND_EMR_LINKED_CAD.CASE_NUMBER
            and AMBO_EMR_NOCAD.PT_RCD_ID = LND_EMR_LINKED_CAD.PT_RCD_ID
         )
   ;
quit;